/**
 * Test Track - Simple oval track for testing
 *
 * Track layout uses tile IDs from TileRegistry
 * Legend:
 * - 'straight' = Road
 * - 'corner' = Corner
 * - 'start_finish' = Start/Finish line
 * - 'grass' = Grass (slow)
 * - 'wall' = Wall (collision)
 * - 'empty' = Void
 */

export const testTrack = {
  "name": "My Track",
  "width": 60,
  "height": 60,
  "tileSize": 5,
  "layout": [
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_bl",
      "dirt_bl",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_tl",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass_bl",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_bl",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_bl",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_b",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "start_finish",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "grass_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass_bl",
      "grass_tl",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_bl",
      "grass",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "wall",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_bl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_br",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_b",
      "dirt_bl",
      "dirt_b",
      "dirt_b",
      "dirt",
      "dirt_bl",
      "dirt_bl",
      "dirt_b",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_l",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_r",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_t",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt",
      "dirt_tl",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "dirt_tr",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_t",
      "dirt_tl",
      "dirt_tl",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ],
    [
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass",
      "grass"
    ]
  ],
  "checkpoints": [
    {
      "id": 0,
      "position": {
        "x": -106.11881510810734,
        "y": 2,
        "z": 34.452200272661095
      },
      "rotation": {
        "x": 0,
        "y": 0.036569056262808736,
        "z": 0
      },
      "width": 80.29557116451285,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 1,
      "position": {
        "x": -110.68542064167954,
        "y": 2,
        "z": -12.84485968158657
      },
      "rotation": {
        "x": 0,
        "y": -0.3776921974687251,
        "z": 0
      },
      "width": 64.56930119818105,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 2,
      "position": {
        "x": -109.86995363437434,
        "y": 2,
        "z": -41.06001187909843
      },
      "rotation": {
        "x": 0,
        "y": -3.11493229493776,
        "z": 0
      },
      "width": 73.41808858450895,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 3,
      "position": {
        "x": -102.69384131835804,
        "y": 2,
        "z": -73.18938342495728
      },
      "rotation": {
        "x": 0,
        "y": 0.20556534035575713,
        "z": 0
      },
      "width": 78.3024751016751,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 4,
      "position": {
        "x": -81.6547931169164,
        "y": 2,
        "z": -104.99260100298989
      },
      "rotation": {
        "x": 0,
        "y": -2.335363897476946,
        "z": 0
      },
      "width": 88.5883858971656,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 5,
      "position": {
        "x": -35.66245218083362,
        "y": 2,
        "z": -110.2115929081157
      },
      "rotation": {
        "x": 0,
        "y": -1.6135048695114365,
        "z": 0
      },
      "width": 76.39739139397123,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 6,
      "position": {
        "x": 22.00484759273037,
        "y": 2,
        "z": -109.42297994530338
      },
      "rotation": {
        "x": 0,
        "y": -1.5322767201331031,
        "z": 0
      },
      "width": 79.59560485137843,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 7,
      "position": {
        "x": 85.35274998522084,
        "y": 2,
        "z": -110.70087398008548
      },
      "rotation": {
        "x": 0,
        "y": -1.0699400965255663,
        "z": 0
      },
      "width": 86.2719841432808,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 8,
      "position": {
        "x": 92.52884558630038,
        "y": 2,
        "z": -49.703940974671895
      },
      "rotation": {
        "x": 0,
        "y": 0.50416606486182,
        "z": 0
      },
      "width": 75.62536315739462,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 9,
      "position": {
        "x": 68.7172144206333,
        "y": 2,
        "z": -33.88389410208535
      },
      "rotation": {
        "x": 0,
        "y": 1.4251683025179738,
        "z": 0
      },
      "width": 74.17715543587225,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 10,
      "position": {
        "x": 16.853537394786894,
        "y": 2,
        "z": -34.373172607962374
      },
      "rotation": {
        "x": 0,
        "y": 1.3782131454074262,
        "z": 0
      },
      "width": 66.46607424057296,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 11,
      "position": {
        "x": -13.318728442948554,
        "y": 2,
        "z": -22.63045271894044
      },
      "rotation": {
        "x": 0,
        "y": 0.9078591213490645,
        "z": 0
      },
      "width": 60.42117038331809,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 12,
      "position": {
        "x": -31.25898743901935,
        "y": 2,
        "z": 8.031083481765116
      },
      "rotation": {
        "x": 0,
        "y": 0.07485982319315992,
        "z": 0
      },
      "width": 52.336431241269906,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 13,
      "position": {
        "x": -15.602028278632982,
        "y": 2,
        "z": 40.16044528652366
      },
      "rotation": {
        "x": 0,
        "y": -0.46364742514593954,
        "z": 0
      },
      "width": 59.07938844602324,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 14,
      "position": {
        "x": 37.88573045366762,
        "y": 2,
        "z": 53.482408419053684
      },
      "rotation": {
        "x": 0,
        "y": -1.5857940065242757,
        "z": 0
      },
      "width": 42.63742122882976,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 15,
      "position": {
        "x": 85.35269421196901,
        "y": 2,
        "z": 59.24230740813131
      },
      "rotation": {
        "x": 0,
        "y": -0.705353283280924,
        "z": 0
      },
      "width": 43.269783655982515,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 16,
      "position": {
        "x": 81.2753546055638,
        "y": 2,
        "z": 108.65960473895095
      },
      "rotation": {
        "x": 0,
        "y": 0.5663295951464056,
        "z": 0
      },
      "width": 62.618432351126685,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 17,
      "position": {
        "x": 25.33438672496986,
        "y": 2,
        "z": 115.34642252622506
      },
      "rotation": {
        "x": 0,
        "y": 1.608657022389162,
        "z": 0
      },
      "width": 43.08746444128187,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 18,
      "position": {
        "x": -27.17940060052493,
        "y": 2,
        "z": 117.3032592471617
      },
      "rotation": {
        "x": 0,
        "y": 1.6192582622396678,
        "z": 0
      },
      "width": 40.4952188898655,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 19,
      "position": {
        "x": -81.3286471772434,
        "y": 2,
        "z": 107.19177536897107
      },
      "rotation": {
        "x": 0,
        "y": 2.4262553033874585,
        "z": 0
      },
      "width": 52.71721268685734,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 20,
      "position": {
        "x": -103.67241489474871,
        "y": 2,
        "z": 70.16962268873033
      },
      "rotation": {
        "x": 0,
        "y": 2.823314351268856,
        "z": 0
      },
      "width": 59.41431002881868,
      "height": 10,
      "isFinishLine": false
    },
    {
      "id": 21,
      "position": {
        "x": -105.14025462019802,
        "y": 2,
        "z": 57.44835126729809
      },
      "rotation": {
        "x": 0,
        "y": 3.135710368865806,
        "z": 0
      },
      "width": 55.452664215835355,
      "height": 10,
      "isFinishLine": true
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": "rock",
      "position": {
        "x": -160.1576107593395,
        "y": 0,
        "z": 47.29705078208907
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 1,
      "type": "rock",
      "position": {
        "x": -148.25180726044545,
        "y": 0,
        "z": -115.79626668288668
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 2,
      "type": "rock",
      "position": {
        "x": -53.65762251379478,
        "y": 0,
        "z": -154.61251003035753
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 3,
      "type": "rock",
      "position": {
        "x": 97.03994034673141,
        "y": 0,
        "z": 7.338786449667893
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 4,
      "type": "rock",
      "position": {
        "x": 133.41037829820212,
        "y": 0,
        "z": -143.68517200148054
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 5,
      "type": "rock",
      "position": {
        "x": 138.62924338637666,
        "y": 0,
        "z": 143.35896865390976
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 6,
      "type": "rock",
      "position": {
        "x": 146.4577530136195,
        "y": 0,
        "z": 60.83380828161925
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 7,
      "type": "rock",
      "position": {
        "x": -4.239495704240603,
        "y": 0,
        "z": 161.78866525350338
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 48.8428629217633,
        "y": 39.074290337410645,
        "z": 48.8428629217633
      }
    },
    {
      "id": 8,
      "type": "rock",
      "position": {
        "x": -147.92562111696634,
        "y": 0,
        "z": 144.8268514384569
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 70.33372260733914,
        "y": 56.26697808587132,
        "z": 70.33372260733914
      }
    },
    {
      "id": 9,
      "type": "rock",
      "position": {
        "x": -160.320704481325,
        "y": 0,
        "z": 110.57727712985641
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 45.01358246869705,
        "y": 36.010865974957646,
        "z": 45.01358246869705
      }
    },
    {
      "id": 10,
      "type": "rock",
      "position": {
        "x": -151.187485082265,
        "y": 0,
        "z": 90.35371345822787
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 28.80869277996612,
        "y": 23.046954223972897,
        "z": 28.80869277996612
      }
    },
    {
      "id": 11,
      "type": "rock",
      "position": {
        "x": -156.7326553745931,
        "y": 0,
        "z": 69.80395908616804
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 28.80869277996612,
        "y": 23.046954223972897,
        "z": 28.80869277996612
      }
    },
    {
      "id": 12,
      "type": "rock",
      "position": {
        "x": -155.7541000666667,
        "y": 0,
        "z": 18.103355366847204
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 13,
      "type": "rock",
      "position": {
        "x": -156.73265397180586,
        "y": 0,
        "z": -36.043627200801026
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 14,
      "type": "rock",
      "position": {
        "x": -127.70202461339623,
        "y": 0,
        "z": -140.42338933568664
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 15,
      "type": "rock",
      "position": {
        "x": -83.99298597996447,
        "y": 0,
        "z": -151.51374672130538
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 16,
      "type": "rock",
      "position": {
        "x": -19.245006825724584,
        "y": 0,
        "z": -159.17910182400175
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 17,
      "type": "rock",
      "position": {
        "x": 109.92498311966686,
        "y": 0,
        "z": -153.6339235296127
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 18,
      "type": "rock",
      "position": {
        "x": 42.404308754756414,
        "y": 0,
        "z": -160.48384918373534
      },
      "rotation": {
        "x": 0,
        "y": 3.141592653589793,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 19,
      "type": "rock",
      "position": {
        "x": 145.9685318607498,
        "y": 0,
        "z": -114.98078520089841
      },
      "rotation": {
        "x": 0,
        "y": 3.9269908169872414,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 20,
      "type": "rock",
      "position": {
        "x": 128.35442519623228,
        "y": 0,
        "z": -5.055889903625186
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 21,
      "type": "rock",
      "position": {
        "x": 148.90341377650412,
        "y": 0,
        "z": 89.36978409039835
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 22,
      "type": "rock",
      "position": {
        "x": 141.0756664201789,
        "y": 0,
        "z": 116.77476287781691
      },
      "rotation": {
        "x": 0,
        "y": 2.356194490192345,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 23,
      "type": "rock",
      "position": {
        "x": 114.32830832556441,
        "y": 0,
        "z": 155.75405039707923
      },
      "rotation": {
        "x": 0,
        "y": 3.141592653589793,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 24,
      "type": "rock",
      "position": {
        "x": 23.32231802733356,
        "y": 0,
        "z": 159.99447208161422
      },
      "rotation": {
        "x": 0,
        "y": 3.141592653589793,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 25,
      "type": "rock",
      "position": {
        "x": -32.45554432206266,
        "y": 0,
        "z": 162.930148076781
      },
      "rotation": {
        "x": 0,
        "y": 3.9269908169872414,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 26,
      "type": "rock",
      "position": {
        "x": 51.04815641690399,
        "y": 0,
        "z": 159.34209962654296
      },
      "rotation": {
        "x": 0,
        "y": 3.9269908169872414,
        "z": 0
      },
      "scale": {
        "x": 41.48451760315121,
        "y": 33.187614082520966,
        "z": 41.48451760315121
      }
    },
    {
      "id": 27,
      "type": "rock",
      "position": {
        "x": 69.96696582640917,
        "y": 0,
        "z": 153.79693358658474
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 28,
      "type": "rock",
      "position": {
        "x": 88.5595857756106,
        "y": 0,
        "z": 157.0587960002681
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 29,
      "type": "rock",
      "position": {
        "x": 123.13534545068187,
        "y": 0,
        "z": 144.663718262199
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 30,
      "type": "rock",
      "position": {
        "x": 102.9117886667518,
        "y": 0,
        "z": 149.55651228971647
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 31,
      "type": "rock",
      "position": {
        "x": 118.07393029478905,
        "y": 0,
        "z": 23.33777675606244
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 32,
      "type": "rock",
      "position": {
        "x": 129.16990399056522,
        "y": 0,
        "z": -27.562772766711902
      },
      "rotation": {
        "x": 0,
        "y": 4.71238898038469,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 33,
      "type": "rock",
      "position": {
        "x": 138.6293251438702,
        "y": 0,
        "z": -43.87210946348343
      },
      "rotation": {
        "x": 0,
        "y": 5.497787143782138,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 34,
      "type": "rock",
      "position": {
        "x": 143.34011367893152,
        "y": 0,
        "z": -92.74358770512487
      },
      "rotation": {
        "x": 0,
        "y": 5.497787143782138,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 35,
      "type": "rock",
      "position": {
        "x": 138.14005635101907,
        "y": 0,
        "z": -79.1002637738732
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 36,
      "type": "rock",
      "position": {
        "x": 146.2947155646375,
        "y": 0,
        "z": -60.1814325484134
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 26.55009126601678,
        "y": 21.240073012813422,
        "z": 26.55009126601678
      }
    },
    {
      "id": 37,
      "type": "rock",
      "position": {
        "x": 144.98996910797933,
        "y": 0,
        "z": -60.833805999554116
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 38.23213142306415,
        "y": 30.585705138451324,
        "z": 38.23213142306415
      }
    },
    {
      "id": 38,
      "type": "rock",
      "position": {
        "x": 130.95856454166486,
        "y": 0,
        "z": 34.41321873593007
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 38.23213142306415,
        "y": 30.585705138451324,
        "z": 38.23213142306415
      }
    },
    {
      "id": 39,
      "type": "rock",
      "position": {
        "x": -113.67625586053332,
        "y": 0,
        "z": 154.61232166910864
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 38.23213142306415,
        "y": 30.585705138451324,
        "z": 38.23213142306415
      }
    },
    {
      "id": 40,
      "type": "rock",
      "position": {
        "x": -92.14776354957156,
        "y": 0,
        "z": 156.24333843408382
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 30.585705138451324,
        "y": 24.46856411076106,
        "z": 30.585705138451324
      }
    },
    {
      "id": 41,
      "type": "rock",
      "position": {
        "x": -52.02684553328166,
        "y": 0,
        "z": 159.1790146901948
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 30.585705138451324,
        "y": 24.46856411076106,
        "z": 30.585705138451324
      }
    },
    {
      "id": 42,
      "type": "rock",
      "position": {
        "x": -73.22895594969934,
        "y": 0,
        "z": 156.24333843408382
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 24.46856411076106,
        "y": 19.57485128860885,
        "z": 24.46856411076106
      }
    },
    {
      "id": 43,
      "type": "rock",
      "position": {
        "x": -152.32781095025865,
        "y": 0,
        "z": 1.1423508197332737
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 24.46856411076106,
        "y": 19.57485128860885,
        "z": 24.46856411076106
      }
    },
    {
      "id": 44,
      "type": "rock",
      "position": {
        "x": -150.37200662460546,
        "y": 0,
        "z": -15.493853752932132
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 24.46856411076106,
        "y": 19.57485128860885,
        "z": 24.46856411076106
      }
    },
    {
      "id": 45,
      "type": "rock",
      "position": {
        "x": -152.98150878858837,
        "y": 0,
        "z": -58.87668018567599
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 24.46856411076106,
        "y": 19.57485128860885,
        "z": 24.46856411076106
      }
    },
    {
      "id": 46,
      "type": "rock",
      "position": {
        "x": -151.67676055716947,
        "y": 0,
        "z": -83.01449814827888
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 35.234732319495926,
        "y": 28.187785855596744,
        "z": 35.234732319495926
      }
    },
    {
      "id": 47,
      "type": "rock",
      "position": {
        "x": -105.68441298878764,
        "y": 0,
        "z": -147.92568616645718
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 35.234732319495926,
        "y": 28.187785855596744,
        "z": 35.234732319495926
      }
    },
    {
      "id": 48,
      "type": "rock",
      "position": {
        "x": -132.7579237189736,
        "y": 0,
        "z": -125.41878705634068
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 35.234732319495926,
        "y": 28.187785855596744,
        "z": 35.234732319495926
      }
    },
    {
      "id": 49,
      "type": "rock",
      "position": {
        "x": -146.78395851754846,
        "y": 0,
        "z": -96.06196974320525
      },
      "rotation": {
        "x": 0,
        "y": -0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 35.234732319495926,
        "y": 28.187785855596744,
        "z": 35.234732319495926
      }
    },
    {
      "id": 50,
      "type": "rock",
      "position": {
        "x": 2.772601137785202,
        "y": 0,
        "z": -155.59102987100513
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    },
    {
      "id": 51,
      "type": "rock",
      "position": {
        "x": 86.92880737421216,
        "y": 0,
        "z": -155.26484297233654
      },
      "rotation": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    },
    {
      "id": 52,
      "type": "rock",
      "position": {
        "x": 18.42956982852797,
        "y": 0,
        "z": -155.91721677074003
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    },
    {
      "id": 53,
      "type": "rock",
      "position": {
        "x": 68.009970720361,
        "y": 0,
        "z": -156.2434036715366
      },
      "rotation": {
        "x": 0,
        "y": 0.7853981633974483,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    },
    {
      "id": 54,
      "type": "rock",
      "position": {
        "x": 57.89817649983935,
        "y": 0,
        "z": -151.02441338645303
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    },
    {
      "id": 55,
      "type": "rock",
      "position": {
        "x": 13.210579691349913,
        "y": 0,
        "z": -152.00297404415838
      },
      "rotation": {
        "x": 0,
        "y": 1.5707963267948966,
        "z": 0
      },
      "scale": {
        "x": 26.62333328088523,
        "y": 21.298666624708183,
        "z": 26.62333328088523
      }
    }
  ],
  "skybox": "default",
  "waypoints": [
    {
      "id": 0,
      "position": {
        "x": -107.96776681446579,
        "y": 0,
        "z": 31.232363404377235
      }
    },
    {
      "id": 1,
      "position": {
        "x": -114.81768023642843,
        "y": 0,
        "z": -3.6695994738227036
      }
    },
    {
      "id": 2,
      "position": {
        "x": -115.14386326377866,
        "y": 0,
        "z": -35.63589391954899
      }
    },
    {
      "id": 3,
      "position": {
        "x": -100.4654592640513,
        "y": 0,
        "z": -61.07846210839348
      }
    },
    {
      "id": 4,
      "position": {
        "x": -90.51675699526163,
        "y": 0,
        "z": -92.88165895149052
      }
    },
    {
      "id": 5,
      "position": {
        "x": -43.21967236430281,
        "y": 0,
        "z": -106.90769396434521
      }
    },
    {
      "id": 6,
      "position": {
        "x": 34.24280297297904,
        "y": 0,
        "z": -108.8650112996906
      }
    },
    {
      "id": 7,
      "position": {
        "x": 82.5251974031412,
        "y": 0,
        "z": -104.2981981116547
      }
    },
    {
      "id": 8,
      "position": {
        "x": 101.44407269322608,
        "y": 0,
        "z": -75.26756941754464
      }
    },
    {
      "id": 9,
      "position": {
        "x": 87.74421359587527,
        "y": 0,
        "z": -40.69177751351206
      }
    },
    {
      "id": 10,
      "position": {
        "x": 47.29706547630629,
        "y": 0,
        "z": -32.53711135443902
      }
    },
    {
      "id": 11,
      "position": {
        "x": 3.2618681471125086,
        "y": 0,
        "z": -30.579991575214923
      }
    },
    {
      "id": 12,
      "position": {
        "x": -26.421115145552427,
        "y": 0,
        "z": -14.92303472040512
      }
    },
    {
      "id": 13,
      "position": {
        "x": -36.85908384412285,
        "y": 0,
        "z": 8.888582463685736
      }
    },
    {
      "id": 14,
      "position": {
        "x": -20.875940190803707,
        "y": 0,
        "z": 36.288244536061086
      }
    },
    {
      "id": 15,
      "position": {
        "x": 5.871354445218499,
        "y": 0,
        "z": 49.33570002698262
      }
    },
    {
      "id": 16,
      "position": {
        "x": 40.77331049715667,
        "y": 0,
        "z": 52.27137727782787
      }
    },
    {
      "id": 17,
      "position": {
        "x": 78.28475696204684,
        "y": 0,
        "z": 56.51179982132933
      }
    },
    {
      "id": 18,
      "position": {
        "x": 97.70791109300383,
        "y": 0,
        "z": 77.17700683132907
      }
    },
    {
      "id": 19,
      "position": {
        "x": 80.404948388134,
        "y": 0,
        "z": 111.14805414148182
      }
    },
    {
      "id": 20,
      "position": {
        "x": 37.674525932308484,
        "y": 0,
        "z": 119.95508701028612
      }
    },
    {
      "id": 21,
      "position": {
        "x": -12.231992922289248,
        "y": 0,
        "z": 117.34559650653866
      }
    },
    {
      "id": 22,
      "position": {
        "x": -70.78274868042672,
        "y": 0,
        "z": 115.55149293976658
      }
    },
    {
      "id": 23,
      "position": {
        "x": -92.63701585859911,
        "y": 0,
        "z": 98.26370015798841
      }
    },
    {
      "id": 24,
      "position": {
        "x": -104.3797224555424,
        "y": 0,
        "z": 70.86403912696416
      }
    }
  ]
}